### ISSUE TITLE
遇到的一些bug

### ISSUE THREAD

**Issue by JandyZ22** [xumi1993/bqmail#6]
最近在用bqmail申请数据时遇到的一些bug
1、使用get_event 命令时
```
get_events -b 20070101 -e 20230101 -d -83.8615/129.6152/130/142 -m 5.0 -c GCMT > AGO1evt.lst
usage: get_events [-h] [-b B] [-e E] [-d D] [-r R] [-m M] [-p P] [-c C]
get_events: error: argument -d: expected one argument
```
但是-d后面要是不接空格的话 可以run 查看源码未发现问题
2、最新版bqmail使用mail模块报错，但是老版本可以。
```
Traceback (most recent call last):
  File "/home/jandyz/workspace/Todo/pkikp/bqmailPKIKP5.0.py", line 21, in <module>
    bq.send_mail(
  File "/home/jandyz/miniconda3/envs/jandy/lib/python3.11/site-packages/bqmail/mail.py", line 120, in send_mail
    self.event_mail(**kwargs)
  File "/home/jandyz/miniconda3/envs/jandy/lib/python3.11/site-packages/bqmail/mail.py", line 161, in event_mail
    self.msgs[evt_date] += '.HYPO ~{}~{:.4f}~{:.4f}~{:.1f}~0~0~{}\n'.format(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unknown format code 'f' for object of type 'str'
```

**Comment by xumi1993** [comment]
第一个问题没有办法，只能不加空格。
第二个问题应该是一个bug，但是最近我在休假，要到一月中旬，才能具体定位这个问题。
